# Inventory for Twenty CRM deployment

[twenty_crm]
crm-server ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[twenty_crm:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
