---
app_user: twenty
app_group: twenty
app_home: /home/twenty
app_dir: /home/twenty/twenty-crm

twenty_repo_url: https://github.com/twentyhq/twenty.git
twenty_repo_version: main

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

twenty_app_port: 3000
twenty_server_port: 3000
twenty_server_url: "http://localhost:{{ twenty_app_port }}"

twenty_pg_database_user: postgres
twenty_pg_database_password: "ChangeMe_Str0ngPass!"
twenty_pg_database_name: default

twenty_app_secret: "please-generate-a-long-random-secret-key"

twenty_storage_type: local
twenty_disable_db_migrations: "false"
twenty_tag: latest
